from app.utils.imagenes import guardar_imagen_estandarizada, limpiar_imagenes_huerfanas
from app.utils.evaluador_flujo import evaluar_estado_equipo
from app.utils.replicador import ejecutar_replica_a_verificacion